# **Quiz on 2D Numpy Array**

Consider the following list a, convert it to Numpy Array.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [3]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Calculate the numpy array size.

In [4]:
a.size

12

Access the element on the first row and first and second columns.

In [6]:
a[0][0:2]


array([1, 2])

Perform matrix multiplication with the numpy arrays A and B.

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [10]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
np.dot(a,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])